In [3]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [4]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_wine

print("Everything is working!")

Everything is working!


In [5]:
data = load_wine()

X = data.data
y = data.target

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Classes:", data.target_names)

X shape: (178, 13)
y shape: (178,)
Classes: ['class_0' 'class_1' 'class_2']


In [6]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Data ko training aur testing me divide karna
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# KNN model
knn = KNeighborsClassifier(n_neighbors=5)

# Model train
knn.fit(X_train, y_train)

# Prediction
y_pred = knn.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.7222222222222222


In [7]:
print("Predicted values:")
print(y_pred)

Predicted values:
[2 0 2 0 1 0 2 0 1 0 2 2 0 1 0 1 1 1 0 1 0 1 2 1 1 1 1 2 1 0 0 1 2 0 0 0]


In [10]:
print("Actual values:")
print(y_test)

Actual values:
[0 0 2 0 1 0 1 2 1 2 0 2 0 1 0 1 1 1 0 1 0 1 1 2 2 2 1 1 1 0 0 1 2 0 0 0]


In [11]:
for k in range(1, 16):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)

    y_pred = knn.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)

    print("K =", k, "Accuracy =", accuracy)

K = 1 Accuracy = 0.7777777777777778
K = 2 Accuracy = 0.7222222222222222
K = 3 Accuracy = 0.8055555555555556
K = 4 Accuracy = 0.75
K = 5 Accuracy = 0.7222222222222222
K = 6 Accuracy = 0.7222222222222222
K = 7 Accuracy = 0.6944444444444444
K = 8 Accuracy = 0.7222222222222222
K = 9 Accuracy = 0.7222222222222222
K = 10 Accuracy = 0.7222222222222222
K = 11 Accuracy = 0.75
K = 12 Accuracy = 0.7222222222222222
K = 13 Accuracy = 0.7222222222222222
K = 14 Accuracy = 0.7222222222222222
K = 15 Accuracy = 0.75


In [12]:
y_pred = knn.predict(X_test)

print("Predicted values:")
print(y_pred)

Predicted values:
[0 0 1 0 1 0 2 2 2 0 0 2 0 1 0 1 1 2 0 1 0 1 2 2 1 2 1 2 1 0 0 1 0 0 0 0]


In [13]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[14  0  0]
 [ 0  9  5]
 [ 2  2  4]]


In [14]:
print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.88      1.00      0.93        14
           1       0.82      0.64      0.72        14
           2       0.44      0.50      0.47         8

    accuracy                           0.75        36
   macro avg       0.71      0.71      0.71        36
weighted avg       0.76      0.75      0.75        36



In [15]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print("Predicted values:")
print(y_pred)

Predicted values:
[2 0 2 0 1 0 1 2 0 0 2 2 0 1 0 1 1 1 0 1 0 1 2 2 1 2 1 2 1 0 0 1 2 0 0 0]


In [16]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8055555555555556


In [17]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[12  0  2]
 [ 1 11  2]
 [ 1  1  6]]


In [18]:
print("Classification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.86      0.86        14
           1       0.92      0.79      0.85        14
           2       0.60      0.75      0.67         8

    accuracy                           0.81        36
   macro avg       0.79      0.80      0.79        36
weighted avg       0.82      0.81      0.81        36

